language: java
dist: trusty
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.m2
branches:
  only:
    - master
before_install:
  - unset GEM_PATH
env:
  global:
    - MAVEN_OPTS="-XX:MaxPermSize=512m -Xmx2g"
install:
  - sudo apt-get install graphviz
script: mvn clean install -Pqulice --quiet --batch-mode --errors
